name: Set build version number

on:
  workflow_dispatch:
    inputs:
      runTests:
        description: 'run tests'
        required: false
        default: 'true'
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
        
env:
  DoRunTests: ${{ github.event.inputs.runTests }}
  Version: ${{ github.event.inputs.version }}

jobs:
  mainbuild:
    runs-on: windows-latest
    outputs:
      version1: ${{ env.Version }}
    steps:

      - name: Run Tests
        run: |
          echo "${{ env.DoRunTests }}"
        shell: powershell
      - name: Set build number
        run: |
          $version= "21.10.0.81"
          echo "::set-output name=version1::$version"
        shell: powershell
      - name: Trigger deploy workflow
        uses: ./.github/workflows/deploy.yml
        with:
          version1: ${{ needs.mainbuild.outputs.version1 }}
    
