name: Trigger  pipeline
on:
  workflow_dispatch: # manual trigger
    inputs:
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
      sanityTest:
        description: 'Run Sanity checks'
        required: false
        default: 'true'
      regressionTest:
        description: 'Run Regression test suite'
        required: false
        default: 'true'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use custom action
        uses: ./.github/actions/my-custom-action
        with:
          version: ${{ github.event.inputs.version }}

      - name: Deploy the app
        run: |
          echo "Deploying version: ${{ inputs.version1 }}"
          # add deployment steps here

      
