name: Triggering Jenkins Pipeline
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
      sanityTest:
        description: 'Run Sanity checks'
        required: false
        default: 'true'
      regressionTest:
        description: 'Run Regression test suite'
        required: false
        default: 'true'
   
env:
  build_number: '99.9.9.9999'
  DoSanityTests: ${{ github.event.inputs.sanityTest }}
  DoRegressionTests: ${{ github.event.inputs.regressionTest }} 
  
jobs:
  job1:
      runs-on: windows-latest
      # Map a step output to a job output
      outputs:
        number: ${{ steps.step1.outputs.version }}
      steps:
        - name : set Version
          id: step1
          run: |
            $version1 = "99.0.0.0"
            echo "build_number=$version1" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            echo "version=${{env.build_number}}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - name : Get Version 
        env:
          Version: ${{needs.job1.outputs.number}}
        run: echo "${{env.Version}} ${{env.DoSanityTests}} ${{env.DoRegressionTests}} ${{env.build_number}}"
      - name: trigger pipeline
        run:  |
          curl -X POST http://153.78.126.84:8080/job/CFC-Build-Deployment/job/Dev/job/1/buildWithParameters --user jenkinsuser:11fc28771d771bcc22a15cb8014d07d677 --data token=github_workflow --data pass_param="yes" --data name="foo"
