name: Triggering Jenkins Pipeline
on:
  workflow_dispatch: # manual trigger
    inputs:
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
      sanityTest:
        description: 'Run Sanity checks'
        required: false
        default: 'true'
      regressionTest:
        description: 'Run Regression test suite'
        required: false
        default: 'true'
   
env:
  build_number: '99.9.9.9999'
  DoSanityTests: ${{ github.event.inputs.sanityTest }}
  DoRegressionTests: ${{ github.event.inputs.regressionTest }} 
  
jobs:
  job1:
      runs-on: windows-latest
      # Map a step output to a job output
      outputs:
        build_number: ${{ steps.step1.outputs.version1 }}
      steps:
        - name : set Version
          id: step1
          run: |
            $version = "21.10.0.81"
            echo "env.build_number=$version"
            echo "${{ github.event.inputs.version }}"
            echo "version1=env.build_number" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name : Get Version 
        env:
          Version: ${{needs.job1.outputs.build_number}}
        run: echo "${{env.Version}} ${{env.DoSanityTests}} ${{env.DoRegressionTests}}"
