name: Triggering Jenkins Pipeline
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
      sanityTest:
        description: 'Run Sanity checks'
        required: false
        default: 'true'
      regressionTest:
        description: 'Run Regression test suite'
        required: false
        default: 'true'
   
env:
  build_number: '99.9.9.9999'
  DoSanityTests: ${{ github.event.inputs.sanityTest }}
  DoRegressionTests: ${{ github.event.inputs.regressionTest }} 
  
jobs:
  job1:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        number: ${{ steps.step1.outputs.version }}
      steps:
        - name : set Version
          id: step1
          run: |
            echo "version=${{env.build_number}}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name : Get Version 
        env:
          Version: ${{needs.job1.outputs.number}}
        run: echo "${{env.Version}} ${{env.DoSanityTests}} ${{env.DoRegressionTests}}"
      - name: trigger pipeline
        run:  |
          curl -X POST \
          -u jenkinsUser:11fc28771d771bcc22a15cb8014d07d677 \
          -H "Content-Type: application/json" \
          -d '{"parameter": [{"name":"version", "value":${{ env.build_number }} }, {"name":"sanitytest", "value":${{ env.DoSanityTests }} }], {"name":"run_regression", "value":${{ env.DoRegressionTests  }} }]}' \
          "http://153.78.126.84:8080/job/CFC-Build-Deployment/job/Dev/job/build_deploy/build"

