name: Research/QA Build 
on: 
  workflow_dispatch: # manual trigger
    inputs:
      runTests:
        description: 'Run unit tests (true/false)'
        required: false
        default: 'true'

env:
build_number: '99.9.9.9999'

jobs:
  mainbuild:
  runs-on: ubuntu-latest
  outputs:
          version: ${{ env.build_number }}
  steps:
    - name: Set build number
      id: get_version
      run: |
       $version = "99.9.9.0000"
       echo "build_number=$version"
      shell: powershell
  
