name: Triggering Jenkins Job
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new build version'
        required: false
        default: '99.99.99.99'
      sanityTest:
        description: 'Run Sanity checks'
        required: false
        default: 'true'
      regressionTest:
        description: 'Run Regression test suite'
        required: false
        default: 'true'
   
env:
  build_number: '99.9.9.9999'
  DoSanityTests: ${{ github.event.inputs.sanityTest }}
  DoRegressionTests: ${{ github.event.inputs.regressionTest }} 
  
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
      - name: Trigger Jenkins job
        run: |
          curl -X POST https://153.78.126.84/job/CFC-Build-Deployment/job/Dev/job/1/buildWithParameters --user "jenkinsuser:11fc28771d771bcc22a15cb8014d07d677" --data-urlencode "version=${{ env.build_number }}" --data-urlencode "sanityTest=${{ env.DoSanityTests }}"  --data-urlencode "regressionTest=${{ env.DoRegressionTests }}"
